apiVersion: v1
kind: Pod
metadata:
  name: laravel
  annotations:
    bind-mount-options: ./src:Z
spec:
  volumes:
    - name: mysql-config
      hostPath:
        path: ./containers/mysql/my.cnf
        type: File
    - name: mysql-init
      hostPath:
        path: ./containers/mysql/sql
        type: DirectoryOrCreate
    - name: mysql-data
      hostPath:
        path: ./volumes/mysql/data
        type: DirectoryOrCreate
    - name: mysql-logs
      hostPath:
        path: ./volumes/logs/mysql
        type: DirectoryOrCreate
    - name: redis-data
      hostPath:
        path: ./volumes/redis/data
        type: DirectoryOrCreate
    - name: pma-sessions
      hostPath:
        path: ./volumes/pma/sessions
        type: DirectoryOrCreate
    - name: apps-dir
      hostPath:
        path: ./src
        type: DirectoryOrCreate
  containers:
    - name: database
      image: docker.io/library/mysql:8.0
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql:Z
          name: mysql-data
        - mountPath: /var/log/mysql:Z
          name: mysql-logs
        - mountPath: /etc/mysql/conf.d/my.cnf
          name: mysql-config
        - mountPath: /docker-entrypoint-initdb.d
          name: mysql-init
      env:
        - name: MYSQL_DATABASE
          value: laraveldb
        - name: MYSQL_USER
          value: larapuser
        - name: MYSQL_PASSWORD
          value: larapass
        - name: MYSQL_ROOT_PASSWORD
          value: lararoot
    - name: redis
      image: docker.io/library/redis:alpine3.16
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: redis-data
          mountPath: /data
    - name: apps
      image: app-lara:latest
      ports:
        - containerPort: 5173
      volumeMounts:
        - name: apps-dir
          mountPath: /var/www
      env:
        - name: DB_CONNECTION
          value: '${DB_CONNECTION}'
        - name: DB_HOST
          value: '${DB_HOST}'
        - name: DB_PORT
          value: '${DB_PORT}'
        - name: DB_DATABASE
          value: '${DB_DATABASE}'
        - name: DB_USERNAME
          value: '${DB_USERNAME}'
        - name: DB_PASSWORD
          value: '${DB_PASSWORD}'
        - name: REDIS_HOST
          value: '${REDIS_HOST}'
        - name: REDIS_PORT
          value: '${REDIS_PORT}'
    - name: phpmyadmin
      image: docker.io/phpmyadmin/phpmyadmin:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: pma-sessions
          mountPath: /sessions:Z
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: lararoot
        - name: PMA_HOST
          value: database
        - name: PMA_PORT
          value: 3306
        - name: UPLOAD_LIMIT
          value: '5G'
